name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  deploy-docs:
    uses: marius-patrik/DarkFactory/.github/workflows/deploy-docs.yml@darkfactory
    secrets: inherit
