name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: marius-patrik/DarkFactory/.github/workflows/release.yml@02490f3012ad0b91beac0c20c2d807adb1647932
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "02490f3012ad0b91beac0c20c2d807adb1647932"
    secrets: inherit
