name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: marius-patrik/DarkFactory/.github/workflows/release.yml@939f862878dfa6f365e2791cc7b1ad06bcbc3316
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "939f862878dfa6f365e2791cc7b1ad06bcbc3316"
    secrets: inherit
