name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: marius-patrik/DarkFactory/.github/workflows/release.yml@7ecba1617f553e6a34ceb31177e1ac84d08c350f
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "7ecba1617f553e6a34ceb31177e1ac84d08c350f"
    secrets: inherit
